name: FlyingBow-OG
version: '2.1'
main: net.trueog.flyingbowog.FlyingBowOG
authors: [barny1094875, NotAlexNoyle]
api-version: 1.19
depend: [NBTAPI]
commands:
  flyingbow:
    usage: /flyingbow
permissions:
  flyingbow.cangive:
    default: op